### ISSUE TITLE
Change Elm dependency into a peerDependency?

### ISSUE THREAD

**Issue by Herteby** [klazuka/elm-hot-webpack-loader#8]
Today when 0.19.1 was released, I had some issues because the version of elm-hot-webpack-loader I was using had `"elm": "^0.19.0"` as a dependency, which apparantly resulted in the broken `0.19.1` version getting installed, rather than `0.19.1-1`. 

The latest version of elm-hot-webpack-loader uses `"elm": "^0.19.0-no-deps"` though, which apparantly causes `0.19.1-1` to be installed.

It seems kind of random though, maybe it'd be best to make elm a peerDependency instead, like elm-webpack-loader has?
https://github.com/elm-community/elm-webpack-loader/blob/master/package.json

**Comment by klazuka** [comment]
Fixed by #15
